"""Stage-11 Part D: deck_excerpts.md — verbatim, paste-ready slide material.
Reads checkpoints + brain pickles + config (no API). Full prompts are RECONSTRUCTED
from the saved decision record + the actually-cited memories + the config persona using
the real prompts.py templates (retrieved-but-uncited memories are omitted; labeled).
"""
import os
import re
import sys
import pickle
import importlib.util
import datetime

import numpy as np
import pandas as pd
import toml

sys.path.insert(0, os.getcwd())
spec = importlib.util.spec_from_file_location("c16", os.path.join("data-pipeline", "16_canonical_metrics.py"))
C = importlib.util.module_from_spec(spec); spec.loader.exec_module(C)
from puppy import prompts as P  # noqa: E402

TICKERS = ["TSLA", "NFLX", "AMZN", "MSFT", "COIN"]
LAYER_DIRS = {"short": "short_term_memory", "mid": "mid_term_memory",
              "long": "long_term_memory", "reflection": "reflection_memory"}
CITE = [("short_memory_index", "short"), ("middle_memory_index", "mid"),
        ("long_memory_index", "long"), ("reflection_memory_index", "reflection")]


def brain_map(tag):
    base = f"data/07_test_model_output/{tag}/agent_1/brain"
    m = {}
    for ln, ld in LAYER_DIRS.items():
        up = os.path.join(base, ld, "universe_index.pkl")
        if os.path.exists(up):
            for sym, rec in pickle.load(open(up, "rb")).items():
                for r in rec["score_memory"]:
                    m[r["id"]] = {"layer": ln, "date": str(r["date"]), "text": r["text"]}
    return m


def sentiment(text):
    mt = re.search(r"positive score for this news is ([\d.]+)\D+neutral score for this news is "
                   r"([\d.]+)\D+negative score for this news is ([\d.]+)", text)
    if not mt:
        return ""
    pos, neu, neg = (float(mt.group(i).rstrip(".")) for i in (1, 2, 3))
    lab = max((("positive", pos), ("neutral", neu), ("negative", neg)), key=lambda x: x[1])[0]
    return f" [FinBERT: {lab}]"


def clean(text):
    return re.sub(r"\s*The positive score for this news is.*$", "", text).strip()


def cited(refl_day):
    out = []
    for fld, ln in CITE:
        for it in (refl_day.get(fld) or []):
            mid = it.get("memory_index") if isinstance(it, dict) else it
            if mid not in (None, -1):
                out.append((ln, mid))
    return out


def load(tag):
    sd = pickle.load(open(f"data/07_test_model_output/{tag}/agent_1/state_dict.pkl", "rb"))
    return {d: r for d, r in sd["reflection_result_series_dict"].items() if d.year == 2026}


def modes(ticker):
    px = C.env_prices(ticker); days = list(px.index); pl = px.values
    return {days[i]: ("averse" if i >= 3 and (pl[i] - pl[i - 3]) < 0 else "seeking")
            for i in range(len(days))}, px


def reconstruct_prompt(ticker, day, refl_day, mode, bmap, persona):
    inv = P.test_investment_info_prefix.format(symbol=ticker, cur_date=day)
    blocks = {"short": "The short-term information:\n", "mid": "The mid-term information:\n",
              "long": "The long-term information:\n", "reflection": "The reflection-term information:\n"}
    by_layer = {k: [] for k in blocks}
    for ln, mid in cited(refl_day):
        rec = bmap.get(mid)
        if rec:
            by_layer[rec["layer"]].append(f"{mid}. {clean(rec['text'])[:200]}{sentiment(rec['text'])}")
    txt = inv + "\n"
    if by_layer["short"]:
        txt += blocks["short"] + "\n".join(by_layer["short"]) + P.test_sentiment_explanation[:160] + "...\n\n"
    for ln in ("mid", "long", "reflection"):
        if by_layer[ln]:
            txt += blocks[ln] + "\n".join(by_layer[ln]) + "\n\n"
    txt += P.test_momentum_explanation[:140] + "...\n"
    pl = P.persona_averse if mode == "averse" else P.persona_seeking
    txt += pl + "\n"
    head = P.test_prompt.split("${investment_info}")[0]
    return f"PERSONA (character_string_test):\n{persona[:400]}...\n\n" + head.strip() + "\n\n" + txt + \
           '\n[JSON instruction] Respond ONLY with {"investment_decision": buy|sell|hold, '\
           '"summary_reason": ..., "<layer>_memory_index": [{"memory_index": <cited id>}]}'


L = ["# Deck excerpts — FinMem-Ours (verbatim, paste-ready)\n",
     "_Generated by 18_excerpts.py from test checkpoints + brain pickles + config. "
     "Full prompts are reconstructed from the saved decision record + actually-cited "
     "memories + the config persona using the real prompts.py templates "
     "(retrieved-but-uncited memories omitted)._\n"]

# ---- 1. two full prompts (NFLX: one seeking, one averse) ----
bmap = brain_map("NFLX_ours"); refl = load("NFLX_ours"); mmode, px = modes("NFLX")
persona = toml.load("config/nflx_finmem_ours_config.toml")["general"]["character_string_test"]
seek_day = next((d for d in sorted(refl) if mmode.get(d) == "seeking" and cited(refl[d])), None)
av_day = next((d for d in sorted(refl) if mmode.get(d) == "averse" and cited(refl[d])), None)
L.append("## 1. Two full prompts actually driving a decision (NFLX)\n")
for lab, d in [("RISK-SEEKING day", seek_day), ("RISK-AVERSE day", av_day)]:
    if d:
        L.append(f"\n### {lab} — NFLX {d} (decision: **{refl[d].get('investment_decision')}**)\n")
        L.append("```\n" + reconstruct_prompt("NFLX", d, refl[d], mmode[d], bmap, persona) + "\n```")

# ---- 2. three persona-switch reasoning quotes ----
L.append("\n## 2. Persona-switch reasoning quotes (verbatim)\n")
quotes, seen = [], set()
for t in TICKERS:
    rf = load(f"{t}_ours")
    for d in sorted(rf):
        rs = str(rf[d].get("summary_reason", ""))
        if ("risk-averse investor" in rs or "risk-seeking" in rs) and t not in seen:
            quotes.append((t, d, re.sub(r"\s+", " ", rs)[:380])); seen.add(t)
            break
for t, d, q in quotes[:3]:
    L.append(f"\n- **{t} {d}:** “{q}”")

# ---- 3. three extended-reflection insights ----
L.append("\n\n## 3. Extended-reflection insights that reached deep memory\n")
ext = []
for t in TICKERS:
    bm = brain_map(f"{t}_ours")
    for mid, r in bm.items():
        if "extended reflection" in r["text"]:
            conf = re.search(r"confidence=(\w+)", r["text"])
            body = re.sub(r"^\[extended reflection[^\]]*\]\s*", "", r["text"])
            ext.append((t, r["date"], conf.group(1) if conf else "?", body[:300]))
ext_sorted = sorted(ext, key=lambda x: x[1])
for t, d, c, body in [ext_sorted[0], ext_sorted[len(ext_sorted)//2], ext_sorted[-1]][:3]:
    L.append(f"\n- **{t} {d}** (confidence {c}): “{body}”")

# ---- 4. biggest-loss day per ticker ----
L.append("\n\n## 4. Biggest-loss day per ticker — why it chose wrong\n")
for t in TICKERS:
    rf = load(f"{t}_ours"); bm = brain_map(f"{t}_ours"); px = C.env_prices(t)
    pos = C.carry_position(C.decisions(f"{t}_ours")).reindex(px.index).ffill().fillna(0)
    fwd = px.shift(-1) / px - 1.0
    contrib = (pos * fwd).dropna()
    if contrib.empty:
        continue
    d = contrib.idxmin()
    nr = fwd.get(d, np.nan) * 100
    L.append(f"\n### {t} — {d.date() if hasattr(d,'date') else d}: decision "
             f"**{rf.get(d,{}).get('investment_decision','?')}**, next-day **{nr:+.1f}%** "
             f"(held {int(pos.get(d,0))})")
    for ln, mid in cited(rf.get(d, {}))[:4]:
        rec = bm.get(mid)
        if rec:
            L.append(f"- `{rec['layer']}` {mid} ({rec['date']}){sentiment(rec['text'])}: {clean(rec['text'])[:200]}")
        else:
            L.append(f"- `{ln}` {mid} [purged before end-state]")
    reason = re.sub(r"\s+", " ", str(rf.get(d, {}).get("summary_reason", "")))[:260]
    if reason:
        L.append(f"- _reasoning:_ “{reason}”")

# ---- 5. discrepancy block ----
L.append("\n\n## 5. GitHub-code vs paper — discrepancies we found (20-second slide)\n")
L.append("""| # | What the paper/README implies | What the shipped code actually does | Our fix |
|---|---|---|---|
| B7 | FinBERT sentiment labels used correctly | `finbert-tone` is {0:Neutral,1:Positive,2:Negative} but code read pos=score[2] → fed **P(Negative)** as the "positive" score | name-based label mapping |
| B8 | Self-adaptive risk persona (seeking↔averse) | only a static one-sided "risk-seeking" line ships; the two-sided rule is commented out | config-flagged `paper_rule` (3-day CR sign) |
| F2 | Layered memory retains critical info "beyond human limits" | deep layer = 3-day revolving door (entry bar==exit bar + decay), **zero filings ever retained** | disable down-jumps + pure-age recency → retains 1000+ |
| D20 | Decay Q_shallow = 14 (sensitivity-justified) | repo ships Q_shallow = 3 | restored paper value 14 |
| momentum | momentum window described loosely | hardcoded 3-day vs 7-day lookback used inconsistently | observation window set to 7-day cumulative return |
| shorting | long-only narrative | `portfolio.py` lets "Sell" open a costless **short** | unit long-only {0,+1}; Sell = exit only |
| seeding | 10-K/10-Q inform decisions | filings filed just before the window are **never ingested** (boundary gap) | seed latest 10-K/10-Q at sim start, true filedAt |
| **metrics** | (our own first pass) | report used raw decisions as position (hold=flat, sell=SHORT) + dropped the final test day | **canonical: carry-forward unit-long, simple returns, full env series** (Stage-11 audit) |
""")

open("data/09_results/deck_excerpts.md", "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote data/09_results/deck_excerpts.md")
